apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: investment-account-api
  name: investment-account-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment-account-api
  strategy: {}
  template:
    metadata:
      labels:
        app: investment-account-api
    spec:
      containers:
      - image: chrias/account-soap-service
        imagePullPolicy: Never
        name: account-soap-service
        resources: {}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: investment
        - name: API_URI_SCHEME
          value: http
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=account-invest-service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(TEMPO_SERVICE_HOST):$(TEMPO_PORT_55680_TCP_PORT)
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://$(TEMPO_SERVICE_HOST):$(TEMPO_PORT_55680_TCP_PORT)
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: http://$(TEMPO_SERVICE_HOST):$(TEMPO_PORT_55680_TCP_PORT)
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: soapdemo
  name: investment-acct-api-svc
  labels:
    app: investment-account-api
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: investment-account-api