apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camel-account-api
  name: camel-account-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-account-api
  strategy: {}
  template:
    metadata:
      labels:
        app: camel-account-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - image: chrias/camel-account-soap-service
        imagePullPolicy: Never
        name: camel-account-soap-service
        resources: {}
        env:
        - name: API_URI_SCHEME
          value: http
        # TODO need to figure out to configure this. The service that's being created by the operator has to CLUSTER-IP for some reason
        - name: SPRING_ARTEMIS_BROKERURL
          value: tcp://ex-aao-hdls-svc.message.svc.cluster.local:61616
          # value: tcp://10.1.2.174:61616
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=camel-account-api
        # - name: OTEL_EXPORTER_OTLP_ENDPOINT
        #   value: http://$(OPENTELEMETRY_COLLECTOR_SVC_SERVICE_HOST):$(OPENTELEMETRY_COLLECTOR_SVC_SERVICE_PORT)
        # - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        #   value: http://$(OPENTELEMETRY_COLLECTOR_SVC_SERVICE_HOST):$(OPENTELEMETRY_COLLECTOR_SVC_SERVICE_PORT)
        # - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
        #   value: http://$(OPENTELEMETRY_COLLECTOR_SVC_SERVICE_HOST):$(OPENTELEMETRY_COLLECTOR_SVC_SERVICE_PORT)
        # TODO I'm not really sending any metrics to tempo via the OTEL API. I'm using Micrometer. Prove that everything still works without the METRICS_ENDPOINT.
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://tempo.observe.svc.cluster.local:55680
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://tempo.observe.svc.cluster.local:55680
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: http://tempo.observe.svc.cluster.local:55680
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOGGING_LEVEL_IO_OPENTELEMETRY
          value: DEBUG
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: camel-account-api
  name: camel-acct-api-gateway-svc
  namespace: soapdemo
spec:
  clusterIP: 10.105.78.36
  clusterIPs:
  - 10.105.78.36
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30950
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: camel-account-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost