apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-subscriber
  name: account-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-subscriber
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account-subscriber
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - image: chrias/account-event-subscriber
        imagePullPolicy: Never
        name: account-event-subscriber
        resources: {}
        env:
        - name: SPRING_ARTEMIS_BROKERURL
          value: tcp://ex-aao-hdls-svc.message.svc.cluster.local:61616
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=account-event-subscriber
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://tempo.observe.svc.cluster.local:55680
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://tempo.observe.svc.cluster.local:55680
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: http://tempo.observe.svc.cluster.local:55680
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AWS_REGION
          value: us-east-2
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-iam-user-administrator
              key: accessKeyId
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-iam-user-administrator
              key: secretAccessKey
        - name: SQS_ACCOUNT_CREATION_ARN
          valueFrom:
            secretKeyRef:
              name: acct-app-secrets
              key: sqsAccountCreationArn
        - name: AWS_MQ_BROKER
          valueFrom:
            secretKeyRef:
              name: acct-app-secrets
              key: awsMqBroker
        - name: AWS_MQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: acct-app-secrets
              key: awsMqUsernname
        - name: AWS_MQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: acct-app-secrets
              key: awsMqPassword
        - name: S3_ACCOUNT_CREATION_ARN
          valueFrom:
            secretKeyRef:
              name: acct-app-secrets
              key: s3AccountCreationArn
