apiVersion: v1
kind: ConfigMap
metadata:
 name: otel-collector-conf
 labels:
   app: opentelemetry
   component: otel-collector-conf
data:
 config.yaml: |
   receivers:   
     zipkin:
       endpoint: 0.0.0.0:9411
   exporters:
     otlp:
       endpoint: tempo.tracing.svc.cluster.local:55680
       insecure: true
   service:
     pipelines:
       traces:
         receivers: [zipkin]
         exporters: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  strategy: {}
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - image: otel/opentelemetry-collector-contrib
        imagePullPolicy: Never
        name: otel-collector
        volumeMounts:
          - mountPath: /etc/otel/config.yaml
          name: data
          subPath: config.yaml
          readOnly: true
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: soapdemo
  name: otel-collector-svc
  labels:
    app: otel-collector
spec:
  ports:
  - port: 4317
    protocol: TCP
  selector:
    app: otel-collector